spring:
  profiles:
    active: dev #默认为开发环境

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.macro.mall: debug
arthas:
  agent-id: mall-search-${spring.profiles.active}
  tunnel-server: ws://192.168.1.249:7777/ws
  http-port: 0
  telnet-port: 0


